# Makefile

main: kmp naive fsm

kmp: 
	g++ -static -O2 -Wall -Wshadow kmp.cpp -o kmp.o
naive: 
	g++ -static -O2 -Wall -Wshadow naive.cpp -o naive.o
fsm: 
	g++ -static -O2 -Wall -Wshadow fsm.cpp -o fsm.o