# Makefile

main: kmp kmp_c naive

kmp: 
	g++ -static -O2 -Wall -Wshadow kmp.cpp -o kmp.o

kmp_c: 
	g++ -static -O2 -Wall -Wshadow kmp_c.cpp -o kmp_c.o

naive: 
	g++ -static -O2 -Wall -Wshadow naive.cpp -o naive.o
